### ISSUE TITLE
TODO for RPG 1.3

### ISSUE THREAD

**Issue by mrimer** [CaravelGames/drod#126]
Ponderings on things to implement for DROD RPG 1.3.  WIP.  Feel free to expand.

- [x] Larger ATK/DEF gems (+3, +10)
- [x] Larger elixir (+1000 HP)
- [x] Detailed Map game element (marks all non-secret rooms explored)
- [X] "My" versions of the various Multiplier variables
- [X] Custom variables in the editor's F4 dialog
- [x] Port the extra flow control commands (Gosub, Else If) from regular DROD to DROD RPG
- [x] Put multi-use plates in
- [x] Port Rain weather effect
- [x] Port CC_RoomLocationText and CC_FlashingText script commands.
- [x] Event checks for atk/def/hp pickups.
- [x] Pushable crate game element (can step on when it can't be pushed; when next to a door, allows stepping up onto the door)
- [x] Global script vars to customize tar/mud/gel/roach queen spawn entity type
- [x] Script command: "Set monster var _attribute_ at (x,y) to _value_"
- [x] Function primitives.  _EnemySTAT(x,y,stat) and many more.
- [x] Put single use plates and breakable orbs in (separate from multi-use because I assume this needs addition room data stuff)
- [x] Tree-like saved game organization

**Comment by kieranmillar** [comment]
Given DROD RPG has the multiplier, I'm not sure larger stat gems need to break down in that way, but +2, +3 and +5 would be nice ones to have that would allow you a large range of values given the multiplier.

Another top tier of HP potion, maybe with base 1000 HP would be nice though.

I have also gone through some historical Feature Request threads and bumped some that might be worthy of consideration: https://forum.caravelgames.com/viewboard.php?BoardID=276

**Comment by yhou8** [comment]
The score verification bug is a big one but the fix is more for an internal rather than public release. It's thread contains some suggested code fixes although contributors cannot really test it.

From the requests board the tree view for saves feature jumps out as a potentially big improvement to QoL. The thread already has quite a bit of discussion but it could be bumped to see if another round could help nail down the design.

**Comment by mrimer** [comment]
> The score verification bug is a big one but the fix is more for an internal rather than public release. It's thread contains some suggested code fixes although contributors cannot really test it.

I concur this is an important bug to fix.  We don't need to plan this fix for the next major version, 1.3.  It can be fixed anytime.

Apologies for the confusion. This topic is intended to make a list for version-breaking changes that could be introduced into new level sets starting with version 1.3.  We would need to implement such changes before version 1.3 is released.

> From the requests board the tree view for saves feature jumps out as a potentially big improvement to QoL. The thread already has quite a bit of discussion but it could be bumped to see if another round could help nail down the design.

This does sound like a helpful improvement.  Would you please bump the topic for visibility if needed?

**Comment by Hypexion** [comment]
A few ideas:

- Port the extra flow control commands (Gosub, Else If) from regular DROD to DROD RPG
- Put multi-use plates in
- Put single use plates and breakable orbs in (separate from multi-use because I assume this needs addition room data stuff)
- Custom variables in the editor's F4 dialog ([thread](http://forum.caravelgames.com/viewtopic.php?TopicID=41659))
- Item collection events ([thread](http://forum.caravelgames.com/viewtopic.php?TopicID=40968))
- "My" versions of the various Multiplier variables ([thread](http://forum.caravelgames.com/viewtopic.php?TopicID=44804))

**Comment by mrimer** [comment]
I'm working on porting rain.

**Comment by mrimer** [comment]
Added detailed map element.

**Comment by kieranmillar** [comment]
Looking back at my last comment after all this time, I have changed my mind on new stat gems being in +2, +3 and +5 varieties. +3 and +10, or +3, +5 and +15 as you originally suggested sound much more useful. 2 gems don't use up enough space on their own to warrant a new variety, +3 feels like the better starting place.

**Comment by mrimer** [comment]
Cool. That makes sense to me.  Okay, let's start with +3.

Now...in that vein, let's decide whether a +5 is worth having if we have a +3, or should we jump up to +10 for the next one.

**Comment by kieranmillar** [comment]
It probably makes sense to think about which grouping is most convenient in terms of number of gems you need to place to reach certain values. So let's list them out and see which one feels best. Here's a list of how many gems you need to place to reach a certain value. First number is 1, 3, 5 grouping, second is 1, 3, 10 grouping, number in brackets is how fewer pickups you need to place to reach that amount of stat (larger positive number is better):

1. 1 - 1 (0)
2. 2 - 2 (0)
3. 1 - 1 (0)
4. 2 - 2 (0)
5. 1 - 3 (2)
6. 2 - 2 (0)
7. 3 - 3 (0)
8. 2 - 4 (2)
9. 3 - 3 (0)
10. 2 - 1 (-1)
11. 3 - 2 (-1)
12. 4 - 3 (-1)
13. 3 - 2 (-1)
14. 4 - 3 (-1)
15. 3 - 4 (1)
16. 4 - 3 (-1)
17. 5 - 4 (-1)
18. 4 - 5 (1)
19. 5 - 4 (-1)
20. 4 - 2 (2)

1, 3, 10 feels like a better grouping to me. 1, 3, 5 doesn't save placing any number of pickups for most small numbers and is mostly consistently worse if you ever want to have a large stat cache.

**Comment by mrimer** [comment]
@kieranmillar , I like the methodology you applied to evaluate which combination is more effective!  This makes sense to me.  I'll do 1, 3, 10.

**Comment by mrimer** [comment]
@Hypexion , it's possible the single-use plates and orbs will just work.  Please go ahead and try them!

**Comment by Hypexion** [comment]
> 
> @Hypexion , it's possible the single-use plates and orbs will just work. Please go ahead and try them!

I've gone ahead and tried them.

Broken orbs work, but have no graphics, leading to beeps and nothing being drawn on their tiles (and they are drawn as snake tails in the tile selector). Cracked orbs function almost as expected, however they are completely destroyed when stabbed, rather than becoming broken obs. Neither interact with beams. They also stay removed from the room if the player leaves and returns. My feeling is that we probably want to keep the cracked -> broken behavior, but I'm not sure about beams.

Single-use plates work, but again lack graphics, appearing as multi-use plates in rooms, and east facing evil eyes in the tile selector. More signifigantly, they don't remain inactive if the player leaves the room and returns. Since every other element in DROD RPG has permanence, this will need a solution.

**Comment by mrimer** [comment]
@Hypexion , thanks for checking.  I'll work on these.

**Comment by mrimer** [comment]
At this point in time, the 1.3 branch has all new functionality I'm currently envisioning (see above list).

I'll plan to provide an alpha full game installer for 1.3 on the forum so registered users can start trying everything out that's in 1.3.  From that point, dev binaries can be provided to patch the install with the latest functionality.
