### ISSUE TITLE
TODO for 5.1.1

### ISSUE THREAD

**Issue by EvidentlyCube** [CaravelGames/drod#70]
I needed a place where I wanted to list a bunch of things to investigate and fix before 5.1.1 lands. A lot of the stuff is threads that were assigned to me for years and I wanted to clean it up. 

So the list is huge and feel free to take stuff from it to work on. **Keep in mind that** some of the things in this list might be feature requests, might've been already fixed but never tested, might be a change that has to be postponed until 5.2, might be not something we want to implement. 

- [x] [Various ways to permanently soft-lock a player in DROD](http://forum.caravelgames.com/viewtopic.php?TopicID=42203)
- [x] [Undo from restore is inconsistent](http://forum.caravelgames.com/viewtopic.php?TopicID=38017)
- [x] [Set Player Weapon _MyScript injection](http://forum.caravelgames.com/viewtopic.php?TopicID=42307)
- [x] [Wait for Item Tarstuffs](http://forum.caravelgames.com/viewtopic.php?TopicID=39585)
- [x] [Cutting and pasting decoys](http://forum.caravelgames.com/viewtopic.php?TopicID=27425)
- [x] [Room clear sound absence confusing with UU](http://forum.caravelgames.com/viewtopic.php?TopicID=37774)
- [x] [TSS - sound doesn't play](http://forum.caravelgames.com/viewtopic.php?TopicID=37662)
- [x] [TSS: Speech Issue](http://forum.caravelgames.com/viewtopic.php?TopicID=37653)
- [x] [Pushable Characters On Top Of Walls Allow Wall Walking](http://forum.caravelgames.com/viewtopic.php?TopicID=38302)
- [x] [Switching between clones uses an undo slot](http://forum.caravelgames.com/viewtopic.php?TopicID=38253)
- [x] [Swords held by clones flicker when player invisible. ](http://forum.caravelgames.com/viewtopic.php?TopicID=38214)
- [x] [Brief flash of the entrance room in the wrong style as Entrance Text fades in](http://forum.caravelgames.com/viewtopic.php?TopicID=38187)
- [x] [Editor inconsistences](http://forum.caravelgames.com/viewtopic.php?TopicID=37885)
- [x] [There is no axis label for Alpha Blending effects (I'm assuming EE and TA are AB effects). ](http://forum.caravelgames.com/viewtopic.php?TopicID=37778)
- [x] [Challenges lost when exporting a player](http://forum.caravelgames.com/viewtopic.php?TopicID=39705)
- [x] [Pushing Young Halph into shallow water shows him wading ](http://forum.caravelgames.com/viewtopic.php?TopicID=39612)
- [x] [Funny bug in export player function](http://forum.caravelgames.com/viewtopic.php?TopicID=39587)
- [x] [Right-clicking during placement mode in a dark room causes major rendering issues](http://forum.caravelgames.com/viewtopic.php?TopicID=39474)
- [x] [Guards with staffs](http://forum.caravelgames.com/viewtopic.php?TopicID=39452)
- [x] [Graphical issue (Maybe)](http://forum.caravelgames.com/viewtopic.php?TopicID=39440&page=0#393461)
- [x] [Graphical problem with falling bridges](http://forum.caravelgames.com/viewtopic.php?TopicID=39404)
- [x] [Crash when watching demo](http://forum.caravelgames.com/viewtopic.php?TopicID=39392)
- [x] [Performance issues when undoing moves in a foggy environment](http://forum.caravelgames.com/viewtopic.php?TopicID=39390)
- [x] [Minor demo description bug](http://forum.caravelgames.com/viewtopic.php?TopicID=39365)
- [x] [lightposts destroyed by briar keep shining](http://forum.caravelgames.com/viewtopic.php?TopicID=39320)
- [x] [Crash when restoring in Picross rooms](http://forum.caravelgames.com/viewtopic.php?TopicID=39310)
- [x] [Score upload does not include challenges](http://forum.caravelgames.com/viewtopic.php?TopicID=39309)
- [x] [Problems with backspace](http://forum.caravelgames.com/viewtopic.php?TopicID=39287)
- [x] [Bridges surrounded by shallow water become water if dropped](http://forum.caravelgames.com/viewtopic.php?TopicID=39276)
- [x] [pushing moves & tokens](http://forum.caravelgames.com/viewtopic.php?TopicID=39223)
- [x] [Buttons on Notices panel don't seem to do anything](http://forum.caravelgames.com/viewtopic.php?TopicID=39139)
- [x] [Odd demo to full data transfer weirdness](http://forum.caravelgames.com/viewtopic.php?TopicID=39136)
- [x] [Drod carsges on Lavender Conway level](http://forum.caravelgames.com/viewtopic.php?TopicID=39045)
- [x] [Disappearing/Dying NPCs remain in the pathmap AND Pushable NPCs do not update pathmap](http://forum.caravelgames.com/viewtopic.php?TopicID=42031)
- [x] [Timeclones and weapons stepping off of token](http://forum.caravelgames.com/viewtopic.php?TopicID=38821)
- [x] [Puzzle/Attack music plays while using the editor](http://forum.caravelgames.com/viewtopic.php?TopicID=38775)
- [x] [Fluff and black doors](http://forum.caravelgames.com/viewtopic.php?TopicID=38771)
- [x] [Graphical Glitch when placing Gentryii](http://forum.caravelgames.com/viewtopic.php?TopicID=38767)
- [x] [Dazed animation stays when dazed character dies on the same turn.](http://forum.caravelgames.com/viewtopic.php?TopicID=38762)
- [x] [Building a powder keg removes underlying fuse and vice versa](http://forum.caravelgames.com/viewtopic.php?TopicID=38760)
- [x] [probably not a bug? - TCB demos where I die](http://forum.caravelgames.com/viewtopic.php?TopicID=38757)
- [x] [Renaming holds and the Change Location screen](http://forum.caravelgames.com/viewtopic.php?TopicID=38715)
- [x] [Gentryii do not sink in shallow water](http://forum.caravelgames.com/viewtopic.php?TopicID=38703)
- [x] [Building invalid objects on top of seeding beacons causes assertion beeps](http://forum.caravelgames.com/viewtopic.php?TopicID=38702)
- [x] [Puff and Slayer type NPCs won't move onto monsters](http://forum.caravelgames.com/viewtopic.php?TopicID=38701)
- [x] [Level Editor: Toggle-able force arrow on top of yellow door](http://forum.caravelgames.com/viewtopic.php?TopicID=38671)
- [x] [Graphical glitch with custom weapons](http://forum.caravelgames.com/viewtopic.php?TopicID=38648)
- [x] [Challenges unmarked](http://forum.caravelgames.com/viewtopic.php?TopicID=38635)
- [x] [If and Move To Single Step](http://forum.caravelgames.com/viewtopic.php?TopicID=38550)
- [x] [Demo description incorrect?](http://forum.caravelgames.com/viewtopic.php?TopicID=38547)
- [x] [Game crash](http://forum.caravelgames.com/viewtopic.php?TopicID=38526)
- [x] [Restore screen oddity](http://forum.caravelgames.com/viewtopic.php?TopicID=38498)
- [x] [Avatar oddidity](http://forum.caravelgames.com/viewtopic.php?TopicID=38493)
- [x] [Briar bug](http://forum.caravelgames.com/viewtopic.php?TopicID=38484)
- [x] [Spear bug](http://forum.caravelgames.com/viewtopic.php?TopicID=38475)
- [x] [Temporal Clones incorrectly indicate their path](http://forum.caravelgames.com/viewtopic.php?TopicID=38468)
- [x] [Halph dying](http://forum.caravelgames.com/viewtopic.php?TopicID=38466)
- [x] [Clone and disarm token bug](http://forum.caravelgames.com/viewtopic.php?TopicID=38461)
- [x] [Pushed clones incorrectly die on hot tiles](http://forum.caravelgames.com/viewtopic.php?TopicID=38450)
- [x] [Avatar not updating when switching custom characters](http://forum.caravelgames.com/viewtopic.php?TopicID=38410)
- [x] [Squad horns don't work properly for some player roles. ](http://forum.caravelgames.com/viewtopic.php?TopicID=41233)
- [x] [Various problems with temporal tokens and swords pointing outside room edge](http://forum.caravelgames.com/viewtopic.php?TopicID=41878)
- [x] [Crossing Gentryii Chains](http://forum.caravelgames.com/viewtopic.php?TopicID=42263)

**Comment by mrimer** [comment]
@EvidentlyCube , This is an excellent achievement!  With these quality-of-life issues, you've made the DROD experience so much better.

Are we ready to start talking about 5.1.1 release candidate builds?

**Comment by EvidentlyCube** [comment]
Not quite. There are a few more tasks I want to tackle and a few that are on you that I think are worth looking into and might actually be quite simple to fix (the reason I'd rather delegate them is because I am tired with all the changes and I still want to implement a bunch of awesome new features for 5.2).

**For me:**

- [ ] [Combining and splitting yellow doors](http://forum.caravelgames.com/viewtopic.php?TopicID=40310)
Huh, actually that's the only one. I'll try to get a linux build up again, too.

And ones I think are worth to do before 5.1.1:

 - [ ] http://forum.caravelgames.com/viewtopic.php?TopicID=41477
 - [ ] http://forum.caravelgames.com/viewtopic.php?TopicID=44305
 - [ ] http://forum.caravelgames.com/viewtopic.php?TopicID=41872

**Comment by mrimer** [comment]
All right!  We've knocked these issues off the list.

**Comment by mrimer** [comment]
Putting up a new dev build.  Once we've verified all changes, are we ready to call the build a RC?

**Comment by mrimer** [comment]
@EvidentlyCube , mind if we close this issue?

**Comment by mrimer** [comment]
Closing this issue.
